name: Node-CI Beta

on:
  push:
    branches: [beta]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x, 24.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build # and test
        run: |
          npm ci
          npm run build
        # We don't yet have any tests setup
        #          npm test
        env:
          CI: true

  publish-npm:
    if: github.repository == 'node-alarm-dot-com/node-alarm-dot-com'
    needs: build # only run if build succeeds
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24 # use the minimum required version
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: node .github/workflows/prerelease.js
      - run: npm --no-git-tag-version version pre --preid=beta
      - run: NODE_AUTH_TOKEN="" npm publish --tag=beta
