name: Node-CI

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [released]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build # and test
        run: |
          npm ci
          npm run build
          # We don't have tests
          # npm test
        env:
          CI: true

  publish-npm:
    # publish only if we are on our own repo
    if: github.repository == 'node-alarm-dot-com/node-alarm-dot-com' && github.event_name == 'release'
    needs: build # only run if build succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14 # use the minimum required version
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
